version: 2

sources:
  - name: my_staging_gcp
    database: massive-tuner-338911
    schema: trips_data_all
    tables:
      - name: yellow_tripdata_2019-01
      - name: fhv_tripdata_2019-01
      - name: green_tripdata_external_table
      - name: yellow_tripdata_external_table
